image:
    file: .gitpod.Dockerfile

# Damit die beiden HTTP-Ports nicht nach jedem Neustart des Workspaces neu
# freigegeben werden müssen.
ports:
  - name: Linkshortener
    port: 8080
    visibility: public
  - name: Mongo-Express
    port: 8081
    visibility: public
    