
spring.application.name=Link-Shortener mit MongoDB

# Konfiguration für MongoDB
spring.data.mongodb.uri=mongodb://root:g3h3im@localhost:27017/linkshortener?authSource=admin
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=mongodb://root:g3h3im@localhost:27017/linkshortener?authSource=admin
spring.mongodb.auto-index-creation=true

# Konfigurationen für Logging
logging.file.name=logdatei.log
logging.level.de.eldecker=INFO


# Konfigurationen für Template-Engine "Thymeleaf"
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
